source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.3'

target 'Reindeer_Example' do
    pod "Reindeer", :path => "../"
    
    # use for fetch remote image
    pod 'Kingfisher', '~> 3.0'
    
    # use for programming auto layout
    pod 'SnapKit', '~> 3.0'
end

target 'Reindeer_Tests' do
    pod "Reindeer", :path => "../"

  
end
